// Generated by https://quicktype.io

export interface CreatePlaylistResponse {
    id:             number;
    name:           string;
    created_date:   string;
    updated_date:   string;
    track_count:    number;
    type:           Type;
    length_ms:      number;
    bpm_range:      null[];
    genres:         any[];
    keys:           any[];
    release_images: any[];
    is_public:      boolean;
    is_owner:       boolean;
    followers:      number;
}

export interface Type {
    id:   number;
    name: string;
}
