// Generated by https://quicktype.io

export interface DownloadsResponse {
    next:     string;
    previous: null;
    count:    number;
    page:     string;
    per_page: number;
    results:  DownloadResponse[];
}

export interface DownloadResponse {
    artists:                    Genre[];
    audio_format:               AudioFormat;
    bpm:                        number;
    enabled:                    boolean;
    genre:                      Genre;
    id:                         number;
    image:                      Image;
    initial_download:           boolean;
    is_available_for_streaming: boolean;
    key:                        Key;
    length_ms:                  number;
    mix_name:                   MixName;
    name:                       string;
    new_release_date:           string;
    order_item_download_id:     number;
    pre_order_date:             null | string;
    price:                      Price;
    publish_date:               string;
    purchase_date:              string;
    received_status:            boolean;
    release:                    Genre;
    remixers:                   Genre[];
    sample_url:                 string;
    sample_start_ms:            number;
    sample_end_ms:              number;
    slug:                       string;
    sub_genre:                  null;
    upgrade_fees:               UpgradeFees;
    url:                        string;
    is_hype:                    boolean;
}

export interface Genre {
    id:     number;
    image?: Image;
    name:   string;
    slug?:  string;
    url?:   string;
    label?: Genre;
}

export interface Image {
    id:          number;
    uri:         string;
    dynamic_uri: string;
}

export interface AudioFormat {
    id:   number;
    name: Name;
}

export enum Name {
    Mp3 = "mp3",
}

export interface Key {
    camelot_number: number;
    camelot_letter: CamelotLetter;
    chord_type:     Genre;
    id:             number;
    is_sharp:       boolean;
    is_flat:        boolean;
    letter:         string;
    name:           string;
    url:            string;
}

export enum CamelotLetter {
    A = "A",
    B = "B",
}

export enum MixName {
    ExtendedMix = "Extended Mix",
    FerBRExtendedMix = "Fer BR Extended Mix",
    OriginalMix = "Original Mix",
}

export interface Price {
    code:    Code;
    symbol:  Symbol;
    value:   number;
    display: Display;
}

export enum Code {
    Eur = "EUR",
}

export enum Display {
    The070 = "€0.70",
    The129 = "€1.29",
}

export enum Symbol {
    Empty = "€",
}

export interface UpgradeFees {
    aiff: Price;
}
