// Generated by https://quicktype.io

export interface MyPlaylistsResponse {
    next:     null;
    previous: null;
    count:    number;
    page:     string;
    per_page: number;
    results:  PlaylistResponse[];
}

export interface PlaylistResponse {
    id:             number;
    name:           string;
    created_date:   string;
    updated_date:   string;
    track_count:    number;
    type:           Type;
    length_ms:      number | null;
    bpm_range:      number[];
    genres:         string[];
    keys:           string[];
    release_images: string[];
    is_public:      boolean;
    is_owner:       boolean;
    followers:      number;
}

export interface Type {
    id:   number;
    name: string;
}
